### ISSUE TITLE
Fix Syncing Issues

### ISSUE THREAD

**Issue by colin-axner** [FourthState/plasma-mvp-sidechain#143]
## Summary of bug
 
After a deposit has exitted, the sidechain won't allow any other nodes to sync.

## Expected behavior

Clients should be able to sync at any time in the chain history. 

## Steps to reproduce
 
1. Deposit on rootchain
2. Do include-deposit on sidechain
3. exit deposit
4. attempt to sync

The node will get caught on this [line](https://github.com/FourthState/plasma-mvp-sidechain/blob/dee03e937947c56020a6c1d960d1b3dcbb87ce67/handlers/anteHandler.go#L170)

We need to develop a mechanism such that we gracefully deal with asynchronous settings. I think we should focus on a solution for PoA, but keep in mind how it would be upgrade to nonPoA. 

A couple topics to discuss:
- whether to keep include-deposit, how beneficial is it? Strange behavior on sidechain of txs skipping blk nums because include-deposit
- how can we use specified finality bounds to decrease a low level of crashes
- in what instances would nodes crash/when would it affect security of rootchain

**Comment by AdityaSripal** [comment]
Posted my scheme from discord chat:

turns out this is actually a pretty serious problem. because the validating our application state is time dependent
so somehow syncing nodes need to know at what time (roughly speaking) a tx occurred
this isn't true of most blockchain state machines
we need a way of not just serializing sidechain tx's with each other (what blockchains do)
we also need a way of serializing it with updates on a different blockchain (ETH)
i feel like there can be a natural serialization here
Let's say that rootchain has submitted blocks 1-(N-1)
For block N we can rely exclusively on finalized rootchain state as it existed at the ETHBlockNum that latest block submission happened in (in this simple case it is ETHBlockNum when N-1 was submitted)
this will at least give some coherent serialization between rootchain state updates and sidechain state updates
now if exits happen after block N-1 was submitted, so be it
we just logically consider that block N happens right after block N-1 was submitted and before any subsequent rootchain updates
even if this is not chronologically true
i think so long as the next block gets submitted before any exits that happen after current block submission get finalized, this should all still work

**Comment by AdityaSripal** [comment]
Fixed in #147
