### ISSUE TITLE
Improvements to CLI

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-sidechain#48]
Dependent on #47 

Users should not be aware that plasma chain is UTXO-based. From client-side, it should look like an account system.

**Comment by colin-axner** [comment]
Improvement Suggestion: Add a mapping from a string to account address. This way users simply specify a "name" of the account they would like to spend from instead of an address similar to how go-crypto implements their keybase. But this may be a functionality that should be done by wallet and not in the CLI

**Comment by colin-axner** [comment]
Further suggestions:
- Add a keys command that has the following subcommands: add, delete, import, export, list, update
- Add a way for users to recover their keys by saving a seed
- As per above, add a mapping from a string to address so users can simply specify a key name rather than an address
- Add a cache (db) for storing confirmation signatures that are generated or received. (Maybe this should be with plasmad since that is where the confirm sig would be recieved?)
- Have the sign command prompt the user asking if they would like to finalize any of their pending txs. Should iterate through each displaying relevant information (time included in plasma block, value, send to addr)
- Add a command to display pending txs (txs that haven't had a confirm sent, and/or have a finalization time less than that required for security)
- Add a broadcast confirmation signature command. Should send to node address specified 
- Add a query command with relevant subcommands (block, txs, balance, info, deposits)
- Add a eth command for all rootchain related commands. Checking on status of exits (time left). Maybe add commands for interacting with rootchain (or perhaps this better left for a wallet?)

- Spending utxos should be as simple as possible, should be similar to:
`plasmacli spend --to --value --fee --account(key?/signer?/from?)`

Default use of spend should be to send to one address, and send whatever is leftover in the utxo back to oneself. We should add in different flags or perhaps a different command for spending to two different addresses. 

I think we should consider changing `spend` to `transfer`. I like spend since it keeps the semantics of the sidechain but I think it could be worthwhile to abstract most of the utxo model away from users. 

I think it is important we don't add in a command for automatically sending confirmation signatures upon eth finalization time period, this would be predictable behavior and it wouldn't be that difficult to feed a node wrong info about eth chain for a few minutes.

**Comment by colin-axner** [comment]
Update `plasmacli keys list` to display better given a long account name

**Comment by colin-axner** [comment]
When adding broadcasting confirm sigs, consider adding `SpendFinalized` field to the input that is spent in the transaction
