### ISSUE TITLE
Creating a cluster locally to test 

### ISSUE THREAD

**Issue by vaibhavchellani** [FourthState/plasma-mvp-sidechain#74]
How can i create a cluster of sidechain nodes and test . Underneath i know its a cosmos app , is there a way to run a cluster of multiple cosmos apps locally ? This would indeed help with testing

**Comment by AdityaSripal** [comment]
Do you mean running the same plasma sidechain with multiple nodes? This _may_ not be possible currently because the nodes wouldn't know who the validator is. I think i can fix this over the weekend. In the meantime, I can give you the steps to run a multiple-node testnet.

Follow these steps to create the testnet:

1. Find node_id for each node

```
$ plasmad tendermint show_node_id
de83c1a52f9c2aba189a2d01d7fa3e2e7c1736dd
```

2. Open `~/.plasmad/config/config.toml` and add the other nodes on the network to the persistent_peers field like so, `node_id@ip_address:26656`

```
# .plasmad/config/config.toml
# Comma separated list of nodes to keep persistent connections to
persistent_peers = "c00ce0b868bd5d5576d23f0ad1090f3f478b7961@35.193.21.171:26656, d35da1c7365c5a3345a23d01d1081f4d87634abc@192.168.1.12:26656"
```

3. Set genesis file with the genesis UTXO's you want.

```
 "app_state": {
    "UTXOs": [
      {
        "Address": "0xdc8820baA512f5827a8A5b45a07b0045Da407700",
        "Denom": "100",
        "Position": [
          "0",
          "0",
          "0",
          "1"
        ]
      }
    ]
  }
```

4. Run `plasmad start` for each node

**Comment by AdityaSripal** [comment]
Just verified that this works with 2 computers running the same sidechain. You can manually change the "validators" in genesis.json to have the same value or you can branch off aditya/multi-nodes and add the single validator you want as part of the app state. Will add in examples soon.
