### ISSUE TITLE
plasmad start cause panic: unknown pubkey type: <nil> <nil>

### ISSUE THREAD

**Issue by bobio2018** [FourthState/plasma-mvp-sidechain#91]
I was able to follow the installation steps and use `plasma init` to generate the init files, but validator_pubkey is null for some reason
```
{
  "moniker": "",
  "chain_id": "test-chain-GMWOcq",
  "node_id": "b1652f568d1d102d892fcd7e6dc18b017fb83286",
  "app_message": {
    "genvalidator": {
      "validator_pubkey": null,
      "fee_address": ""
    },
    "UTXOs": null
  }
}
```
It successfully generates the files however then when I run `plasmad start`, it throws error `panic: unknown pubkey type: <nil> <nil>`

```
I[27116-11-27|22:37:22.989] Starting ABCI with Tendermint                module=main 
I[27116-11-27|22:37:22.995] Starting multiAppConn                        module=proxy impl=multiAppConn
I[27116-11-27|22:37:22.996] Starting localClient                         module=abci-client connection=query impl=localClient
I[27116-11-27|22:37:22.996] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[27116-11-27|22:37:22.996] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[27116-11-27|22:37:22.996] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0
I[27116-11-27|22:37:22.996] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
panic: unknown pubkey type: <nil> <nil>

goroutine 1 [running]:
github.com/FourthState/plasma-mvp-sidechain/vendor/github.com/tendermint/tendermint/types.tm2pb.PubKey(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/developer/go/src/github.com/FourthState/plasma-mvp-sidechain/vendor/github.com/tendermint/tendermint/types/protobuf.go:113 +0x472
github.com/FourthState/plasma-mvp-sidechain/app.(*ChildChain).initChainer(0xc0001139d0, 0x4d14f80, 0xc0009cca50, 0xc0004dd380, 0xb, 0x218ca368, 0xed38f236e, 0x0, 0xc000035a60, 0x11, ...)
	/Users/developer/go/src/github.com/FourthState/plasma-mvp-sidechain/app/app.go:120 +0x291
github.com/FourthState/plasma-mvp-sidechain/app.(*ChildChain).initChainer-fm(0x4d14f80, 0xc0009cca50, 0xc0004dd380, 0xb, 0x218ca368, 0xed38f236e, 0x0, 0xc000035a60, 0x11, 0xc0004dd280, ...)
	/Users/developer/go/src/github.com/FourthState/plasma-mvp-sidechain/app/app.go:85 +0xb6
```

**Comment by bobio2018** [comment]
my .plasmad/config/genesis.json
```
{
  "genesis_time": "2018-11-27T12:08:46.846025Z",
  "chain_id": "test-chain-61A067",
  "consensus_params": {
    "block_size": {
      "max_bytes": "22020096",
      "max_gas": "-1"
    },
    "evidence": {
      "max_age": "100000"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }
  },
  "app_hash": "",
  "app_state": {
    "genvalidator": {
      "validator_pubkey": null,
      "fee_address": ""
    },
    "UTXOs": null
  }
}
```

**Comment by bobio2018** [comment]
a bit more research shows the error is related to [this line 113](https://github.com/tendermint/tendermint/blob/c086d0a34102bd42873d20445673ea1d18a539cd/types/protobuf.go#L113) due to passing empty `genesisState.Validator.ConsPubKey` to `ValidatorUpdate`
my question is why my genesis pubKey is empty?

**Comment by colin-axner** [comment]
You can find your validator pubkey in `priv_validator.json`. You can just copy paste the entire pubkey section, here is an [example](https://github.com/FourthState/plasma-mvp-sidechain/blob/a4da513838b9c0bfb85d335ea7810307b3eca72d/docs/testnet-setup/example_genesis.json#L21). You will also want to fill in the `UTXOs` section with addresses you own otherwise no transactions can be sent on the sidechain.

I believe the pubkey field is left intentionally null because you can run a full node which means the validator pubkey would not be the the pubkey in your `priv_validator.json` file. However, if one is running a full node and not a validator, then the genesis.json file has already been generated. Will update soon with better default behavior

**Comment by bobio2018** [comment]
@colin-axner thank you! I have copied my pubKey into `genesis.json` and it is now running.  Two questions please
1. Where can I get the `UTXOs` data from the addresses I own? Do I need to deploy the [rootchain contracts](https://github.com/FourthState/plasma-mvp-rootchain/blob/master/docs/rootchainFunctions.md) to localnet via Ganache and that will give me the `UTXOs` data? 

2. After setting `UTXOs` in genesis.json and start sidechain. How do I test the whole workflow from rootchain (ganache) to running sidechain, for example token staking on rootchain, spending txs on sidechain, and exit sidechain etc.

Is there a documentation I can follow?

many thanks!

**Comment by colin-axner** [comment]
Interaction between the sidechain and rootchain has not been implemented yet, but there is a `rpc` branch currently open addressing this issue. 

Since master/develop branches cannot interact with the rootchain at the moment we have a genesis file so that there exists utxos to spend for testing purposes. You can generate addresses using `plasmacli`

`plasmacli add` allows you to add a new account
`plasmacli list keys`  lists any accounts you have which are stored in ~/.plasmacli/keys
`plasmacli import <keyfile>` allows you to import an unencrypted priv key 

After adding accounts, use the list command to print out your address, copy and paste that address into the genesis file. After starting up `plasmad` you should be able to use the `plasmacli info <address>` or `plasmacli balance <address>` to see that those utxos indeed exist. You can then spend those utxos.   

In about two weeks we should hopefully have the rpc branch merged into master, which will allow you to deploy the rootchain (ganache) and send deposits to the contract. The client code would detect deposits and exits and account for them in the sidechain state. We are still working on automating access to the ganache accounts. 

Our only documentation at the moment is in the docs folder. We will add more documentation on deploying a rootchain contract and running a validator once the rpc connections are finalized.

**Comment by colin-axner** [comment]
Fee address is the ethereum address a validator wants their fees sent too. In this case you can use your own address `0x965dfa534B1bC4a88c60BA4287e4ceaF38eC7B50`. 

Have you ran `plasmad unsafe-reset-all`? If you make modifications to the genesis file you need to reset the blockchain history and restart it from block 1 to take into account the changes.

Let me know if the issue persists

**Comment by bobio2018** [comment]
**update**
i tried with `plasmad unsafe_reset_all` to clear the data then `plasmacli add` another new address `0xCBE12C2c094a773c076F1f2d189c06fAaCD34EDD` and follow the same process above

now `plasmacli info 0xCBE12C2c094a773c076F1f2d189c06fAaCD34EDD` is working

outputs
```
Position: {0 0 0 1} 
Amount: 100 
Denomination: Ether 

Position: {0 0 0 2} 
Amount: 100 
Denomination: Ether 
```
many thanks @colin-axner

**Comment by bobio2018** [comment]
Another questions please, what is the primary design consideration for using a `UTXO` model for sidechain tx? I have been testing cosmos [basecoin](https://github.com/cosmos/cosmos-sdk/tree/v0.26.1-rc1/examples/basecoin) example and [doc](https://cosmos.network/docs/sdk/core/app5.html#directory-structure), it looks like a straightforward account + coins model and token can be transferred between accounts on sidechain.

Does UTXO model offer more mandatory features to enable MVP spec compare to basecoin account model? 
Also does FourthState plan to support EVM on sidechain so it can stake tokens from ethereum rootchain to sidechain, then the tokens can be used for deploying and consuming solidity contracts deployed on sidechain?

**Comment by colin-axner** [comment]
The main reason for using `UTXO` model is simplicity when exiting onto the rootchain. It allows for simple and secure proofs/challenges. Accounts are a nice model especially when integrating with UIs and clients, but become more difficult to work with when addressing block withholding attacks, double spends, etc.

We want to finish a secure, mainnet ready version of mvp before moving forward with more complexity, but once we reach that point we have many projects/features in mind that we would like to add to the plasma architecture. Bringing an EVM to the sidechain is definitely on the list of things we are considering developing in the future. If you would like to stay up to date on our development or let us know what features you'd like to see in the near future, feel free to join our [discord server](https://discord.gg/YTB5A4P)

**Comment by bobio2018** [comment]
thank you @colin-axner , will join discord for future updates
